language: go

env:
 global:
  secure: "jI/QW81yi0obHOqW63wnQd6PVTxZlJoMnRYapNqdUmm8PSBHMxFgrdZNpdz4w0q/xydm6yHJaPcRehH/MBJwHOKnbwhsv0BxnEzqgQC1rLmv+zZdDBW2Kp6rw0OZXRPyR/1kbvgjhZaJTbSXkS08nGnF2/lAgM1EmR9OMw2xuFQ="

matrix:
  allow_failures:
    - go: tip
  fast_finish: true
  include:
    - go: 1.1
    - go: 1.2
    - go: 1.3
    - go: 1.4
    - go: 1.5
    - go: 1.6
    - go: 1.7
    - go: 1.8
    - go: 1.9
      env: FMT_AND_VET=1
    - go: tip

before_script:
  - test "$FMT_AND_VET" != 1 || go get "golang.org/x/tools/cmd/cover"
  - test "$FMT_AND_VET" != 1 || go install "golang.org/x/tools/cmd/cover"
  - test "$FMT_AND_VET" != 1 || go get github.com/mattn/goveralls
  - test "$FMT_AND_VET" != 1 || go install github.com/mattn/goveralls
  - test "$FMT_AND_VET" != 1 || sudo -E $(which go) install -a -race std

script:
  - test "$FMT_AND_VET" != 1 || test -z "$(gofmt -l . | tee /dev/stderr)"
  - test "$FMT_AND_VET" != 1 || go vet .
  - go test -v
  - test "$FMT_AND_VET" != 1 || go test -covermode=count -coverprofile=/tmp/coverage.out
  - test "$FMT_AND_VET" != 1 || go test -v -race .

after_script:
 - test "$FMT_AND_VET" != 1 || $HOME/gopath/bin/goveralls -coverprofile=/tmp/coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN
